
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `auto_chat_text`;
CREATE TABLE `auto_chat_text` (
  `groupId` int(11) NOT NULL DEFAULT '0',
  `chatText` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`groupId`,`chatText`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `auto_chat_text` VALUES ('1', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('1', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('1', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('1', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('1', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('1', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('1', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('1', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('2', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('2', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('2', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('2', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('2', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('2', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('2', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('2', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('3', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('3', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('3', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('3', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('3', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('3', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('3', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('3', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('4', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('4', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('4', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('4', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('4', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('4', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('4', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('4', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('5', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('5', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('5', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('5', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('5', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('5', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('5', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('5', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('6', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('6', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('6', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('6', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('6', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('6', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('6', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('6', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('7', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('7', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('7', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('7', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('7', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('7', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('7', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('7', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('8', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('8', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('8', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('8', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('8', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('8', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('8', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('8', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('9', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('9', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('9', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('9', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('9', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('9', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('9', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('9', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('10', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('10', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('10', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('10', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('10', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('10', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('10', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('10', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('11', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('11', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('11', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('11', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('11', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('11', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('11', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('11', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('12', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('12', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('12', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('12', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('12', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('12', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('12', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('12', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('13', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('13', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('13', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('13', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('13', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('13', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('13', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('13', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('14', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('14', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('14', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('14', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('14', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('14', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('14', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('14', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('15', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('15', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('15', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('15', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('15', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('15', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('15', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('15', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('16', '%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('16', '%player_cabal_loser%! You bring an ill wind!');
INSERT INTO `auto_chat_text` VALUES ('16', '%player_cabal_loser%! You might as well give up!');
INSERT INTO `auto_chat_text` VALUES ('16', 'A curse upon you!');
INSERT INTO `auto_chat_text` VALUES ('16', 'All is lost! Prepare to meet the goddess of death!');
INSERT INTO `auto_chat_text` VALUES ('16', 'All is lost! The prophecy of destruction has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('16', 'The prophecy of doom has awoken!');
INSERT INTO `auto_chat_text` VALUES ('16', 'This world will soon be annihilated!');
INSERT INTO `auto_chat_text` VALUES ('17', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('17', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('17', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('17', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('17', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('17', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('17', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('17', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('18', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('18', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('18', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('18', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('18', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('18', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('18', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('18', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('19', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('19', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('19', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('19', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('19', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('19', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('19', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('19', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('20', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('20', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('20', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('20', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('20', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('20', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('20', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('20', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('21', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('21', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('21', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('21', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('21', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('21', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('21', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('21', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('22', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('22', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('22', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('22', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('22', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('22', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('22', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('22', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('23', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('23', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('23', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('23', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('23', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('23', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('23', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('23', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('24', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('24', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('24', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('24', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('24', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('24', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('24', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('24', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('25', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('25', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('25', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('25', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('25', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('25', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('25', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('25', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('26', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('26', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('26', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('26', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('26', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('26', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('26', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('26', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('27', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('27', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('27', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('27', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('27', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('27', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('27', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('27', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('28', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('28', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('28', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('28', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('28', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('28', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('28', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('28', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('29', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('29', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('29', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('29', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('29', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('29', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('29', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('29', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('30', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('30', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('30', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('30', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('30', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('30', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('30', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('30', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('31', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('31', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('31', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('31', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('31', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('31', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('31', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('31', 'The prophecy of darkness has come to pass!');
INSERT INTO `auto_chat_text` VALUES ('32', '%player_cabal_winner%! I bestow on you the authority of the abyss!');
INSERT INTO `auto_chat_text` VALUES ('32', '%player_cabal_winner%, Darkness shall be banished forever!');
INSERT INTO `auto_chat_text` VALUES ('32', '%player_cabal_winner%, the time for glory is at hand!');
INSERT INTO `auto_chat_text` VALUES ('32', 'All hail the eternal twilight!');
INSERT INTO `auto_chat_text` VALUES ('32', 'As foretold in the prophecy of darkness, the era of chaos has begun!');
INSERT INTO `auto_chat_text` VALUES ('32', 'The day of judgment is near!');
INSERT INTO `auto_chat_text` VALUES ('32', 'The prophecy of darkness has been fulfilled!');
INSERT INTO `auto_chat_text` VALUES ('32', 'The prophecy of darkness has come to pass!');
